title: balanced things
author: harshith reddy
email: your-email@domain.com
description: the new balanced things are to work under such variable conditions using great chnages
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
